### ISSUE TITLE
Gilbert's comment

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/draft-guide-arquillian-managed#10]
- [x] Time should not be 30 min long
- [x] Need to explain what is Arquillian
- [x] maven and gradle instruction should be presented separately 
- [x] following statement sound weird. Why testing in between start and stop server?
```Between the server start and stop messages, you will see the following console output indicating that your test has passed.```
- [x] pom.xml should be formatted properly
- [x] pom.xml should have some comments to indicate which parts relate to Arquillian
- [x] in pom.xml, should use that way to install liberty? Should use the same way as other guides.
- [x] Better create our own classes instead of using someone's sources
  - use simple servlet approach is fine
- [x] it is weird to test by running ```mvn clean install```
- [x] There are several ```here``` links. Should they be spelled out? What is the practice?
- [x] The build.gradle hard-coded the liberty version 18.0.0.1. It is not our practice
```libertyRuntime "io.openliberty:openliberty-runtime:18.0.0.1```

Reference: https://developer.ibm.com/wasdev/docs/getting-started-liberty-arquillian/

**Comment by evelinec** [comment]
The remaining 3 points are not addressed based on our discussion for now.

**Comment by evelinec** [comment]
Addressed in #15
