### ISSUE TITLE
Peer Review - 01/11/2019

### ISSUE THREAD

**Issue by andrewdes** [OpenLiberty/draft-guide-arquillian-managed#16]
### Checklist

- [x] Working instruction and sample code
- [x] Quality of code (best coding practices)
- [ ] Quality and presentation of guide according to Structure and Style Guideline
- [ ] Consistency of guide with template and other guides
- [x] Examples with the right outcomes are provided
- [x] Example with the wrong outcomes, if any, are provided
- [x] Check that all licensing statements are properly stated in all files
- [x] Check that the pom.xml, server.xml, etc files are clean up
- [x] Check that the directories are properly structured
- [x] Test the guide on 3 platforms: Mac, Win, Linux
- [x] If any URL visits, try them on different browsers: Firefox, Chrome, Safari
- [x] If any URL visits, try curl command where applicable
- [x] Ensure that the automation tests are able to run with continuous daily build
EC: The automation is running correctly, just there's no `console.log` to report the build and jdk version info. See issue #19. 

- [x] Ensure that the guide is using the latest version of the liberty-maven-plugin or gradle plugin

---

### General
- [ ] Title: "Testing microservices with Arquillian Managed container" -> I think it should be "with **the** Arquillian Managed container"
EC: It feels like "the" is not needed. If ID review also thinks the same way, will edit it then. 

- [x] When completing the guide, the `mvn clean install` runs successfully from the start directory, but the output is completely different from the output when running in the finish directory. It doesn't even appear that the tests run...
- [x] "Also notice in the configuration that skipTestServer is set to true to skip the test-start-server and test-stop-server goals" but the goals are still ran when running `mvn clean install`
EC: The `test-stop-server` goal was not run. The `test-start-server` started, but it only prints the initial messages, ie, "Using..". The actual actions aren't run. Looks like this is the behaviour for this the `skipTestServer` config. 
- [x] test directory in start does not match test directory in finish
- [x] application in start directory is different than in finish directory
- [x] `InventoryIT.java`, `SystemIT.java` and `pom.xml` have some lines that are too long
- [ ] There is a `build.gradle` file but I don't see anything about gradle mentioned in the guide
- [x] SystemData.java has no copyright
- [ ] I feel like the user doesn't get to do much in the guide. For example in the **Setting up your Arquillian Liberty Managed container** they simply look at two pre-configured files. Perhaps it would be a more meaningful experience if they actually inserted the key parts of the `pom.xml` and `server.xml` file. 
EC: I think the multipane can help with this guide, as the `pom.xml` is really long. It'd be good to have it besides the text describing the sections of codes. However, I don't think we'd be instructing user to insert, to minimize making mistake. The team decided to go with description and showing portion of the code, no inserting code. 

### What you’ll learn
- [ ] "take advantage of features in the **Liberty plugin**..." -> Is it possible to be more specific here (i.e. maven liberty plugin, gradle liberty plugin, etc.).
EC: Not necessary, cus it seems to take away the focus. 
- [x] "...for your java applications." -> "for your **Java** applications
- [x] "Arquillian tests are very similar to the common unit tests, however, Arquillian sets up the test environment and able to handle the application server life cycle for you, so you can focus on writing tests." ->  "...and **is** able to handle the application server life cycle for you, so you can focus on writing tests."
- [ ] "An Arquillian test has three components, @RunWith(Arquillian.class), @Deployment and @Test. Once you have these three components setup, you’ll have everything you need to test your microservices. You will learn more about these components in the test class." -> I feel like these sentences could be condensed. For example: "In this guide you will learn about the three components in an Arquillian test that are required for testing your microservices, `@RunWith(Arquillian.class)`, `@Deployment` and `@Test`. " or something similar.
EC: The sentence you suggests has the different meaning than the original ones. 
- [ ] "Arquillian Liberty Managed container..." -> "**The Arquillian Liberty Managed container..."
EC: doesn't seem necessary. The paragraph now has more content, let me know what you think. 
- [x] "You will learn to configure the inventory service to use the Liberty Arquillian Managed container adaptor with the Maven build tool and develop functional and integration test for the microservices to run in Open Liberty" -> "You will learn **how** to configure the inventory service to use the Liberty Arquillian Managed container adaptor with the Maven build tool and develop functional and integration **tests** for the microservices to run in Open Liberty"

### Getting started
- [x] The user is instructed to run `mvn clean install`, is the `clean` necessary? 

### Setting up your Arquillian Liberty Managed container
- [x] "...and setup the Liberty server.xml file before..." -> `server.xml`. Also, should the path to the server.xml file be included here?
EC: No, because this sentence isn't referring to the file yet in the paragraphs right after it. 
- [x] "All of the Maven configuration takes place in the pom.xml file." -> All of the Maven configuration takes place in the pom.xml file**:**"
- [ ] "You can learn more about the Arquillian Liberty dependency bundles." -> This sentence sounds awkward and should be re-worded if possible.
EC: Any suggestion? Not much can be done as the linked page title is "Arquillian Liberty dependencies". 
- [x] " The Shrinkwrap API allows you to create your test archive which is packaged into a WAR and deployed to the Open Liberty server." -> `WAR` file
EC: I think WAR here is just short form for Web Archive. Added the word "file", but don't think WAR needs to be backticked. 
- [x] "... your arquillian.xml." -> "your arquillian.xml **file**."
- [x] "Also notice in the configuration that skipTestServer is set to true to skip the test-start-server and test-stop-server goals defined in the Liberty Maven Application Parent. " -> "Also, ..."
- [x] "**This** is because Arquillian is managing the server lifecycle when it runs the tests." -> "this" could be ambiguous, should be followed by a noun (i.e. this configuration...)
- [x] "Now that you’re done configuring the build tool, open the src/main/liberty/config/server.xml file." -> file**:**

### Developing Arquillian tests
- [x] "You’re now ready to write your test. You will write Arquillian tests ... " -> These sentences are inconsistent. The first one makes it sound like the user will be writing a single test, the second one makes it appear as though they will be writing multiple. 
- [x] "The microservices code are provided to you under the src/main/java/io/openliberty/guides directory. " -> "The code for the microservices is provided for you in the src/main/java/io/openliberty/guides directory."
- [x] The `src/test/java/it/io/openliberty/guides/inventory/` directory should be provided with a .gitignore file so that the user doesn't have to create it. 
EC: .gitkeep is added
- [x] "...this is necessary, if you don’t want a randomly generated web archive name." -> comma is not needed
- [x] "...inventory service communicates to the system service..." -> "inventory service communicates **with** the system service"
- [x] "The test verifies that the system property for the local and service JVM **should** match." -> "The test verifies that the system property for the local and service JVM match."
- [x] "The test also verifies that the system property stored in the inventory for the local and service JVM **should** match." -> "The test also verifies that the system property stored in the inventory for the local and service JVM match."
- [x] "...which validates that the system property for the local and service JVM **should** match" -> "which validates that the system property for the local and service JVM match"
- [x] "This test case calls the listContents() to.." -> "This test case calls the listContents() **method** to"

### Running the tests
- [x] is the clean in `mvn clean install` necessary?

**Comment by evelinec** [comment]
Thank you @andrewdes for checking the guide again! Will take care of the rest. Thanks.

**Comment by evelinec** [comment]
@andrewdes can you review the fixes for this issue and let me know if there's anything? Thanks.

**Comment by evelinec** [comment]
Automation test is working for this guide and had tested the latest dev build: https://travis-ci.org/OpenLiberty/draft-guide-arquillian-managed/builds/480921082

**Comment by andrewdes** [comment]
I read through the guide again and I am ok with the fixes made and the explanations provided above for not making certain changes. However, I do still have the following feedback:

- [ ] "The code for the microservices are provided to you under the src/main/java/io/openliberty/guides directory" -> The code for the micro services is provided for you in the src/main/java/io/openliberty/guides directory.
- [ ] In the **Developing Arquillian tests** section, there is some inconsistencies between the two links in the "The testGetPropertiesFromEndpoint test case is an integration test..." paragraph. One uses `{WARNAME}` and the other uses `<WARNAME>`, is there a reason for this difference?

**Comment by evelinec** [comment]
Fixed.
