### ISSUE TITLE
Gilbert's feedback

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/draft-guide-arquillian-managed#18]
- [x] All license years should be either `2017, 2019` or `2019`
EC: actually only mark the license with the year 2019 when the file is newly created. ie, the test classes. I don't touch any of the files for the microservices. 
- [x] SystemData misses the copyright section
EC: Fixed. It was missing from the CDI-Intro guide. 
- [x] the System.out.println are not necessary in the tests
- [x] the following elements in the pom.xml can do better as following:
```
<systemPropertyVariables>
    <liberty.test.port>
        ${testServerHttpPort}
    </liberty.test.port>
</systemPropertyVariables>
                            
<summaryFile>
    ${project.build.directory}/test-reports/it/failsafe-summary.xml
</summaryFile>

<reportsDirectory>
    ${project.build.directory}/test-reports/it
</reportsDirectory>
```
- [x] Some codes in the InventoryIT should be wrapped better.
```
        Assert.assertEquals("The system property for the local and remote JVM should matc
h",
                            System.getProperty("os.name"), localhostobj.getString("os.nam
e"));
        System.out.println("Test the system property for the local and service JVM should
match.");


        System.out.println("Test system property for the local and service JVM should mat
ch.");
```
- [x] do we need build.gradle? If yes, need to describe it in the Readme, otherwise remove it
- [x] need to decide whether ask readers to update or create pom.xml and server.xml in start ]
  - my thought was: The pom.xml and server.xml are available in the start.  Readers can run `mvn install liberty:start-server`, and  hit the endpoint urls. After stop the server, tell readers to update the pom.xml and server.xml, and add the test files to learn what need to be changed if they want to create Arquillian tests in our microservice. Then they can run `mvn ....` to make the tests run.

**Comment by evelinec** [comment]
Issue #22 created to handle gradle for the future.

**Comment by evelinec** [comment]
@gkwan-ibm can you review the fixes for this issue and let me know if there's anything? Thanks.

**Comment by gkwan-ibm** [comment]
- [ ] can separate the section to describe the plugins `org.apache.maven.plugins` and `net.wasdev.wlp.maven.plugins` into 2 paragraphs? Now the combined is a bit long
- [ ] avoid to use `<version>[17.0.0.4,)</version>`
- [ ] for the following paragraph, please add `<feature>servlet-xxx</feature>` into the server.xml,  which I didn't add before because I am not aware the servlet feature is required
```
The servlet feature is required during the deployment of the Aquillian tests 
in which servlets are created to perform the in-container testing.
```
- [ ] `You can learn more about the the` has double `the` words
- [ ] `The test server configuration is disable ` should use `disabled`?
- [ ] following `Assert` code still no good
![screen shot 2019-01-17 at 12 10 24 pm](https://user-images.githubusercontent.com/29576299/51335795-f7e1ff80-1a50-11e9-8cf3-de802104fb5f.png)

**Comment by evelinec** [comment]
The first two points were discussed but no change. About describing SystemIT, it's the same as InventoryIT in terms of Arquillian tests.
