### ISSUE TITLE
Fixing the RELEASE keyword used in the parent pom

### ISSUE THREAD

**Issue by evelinec** [OpenLiberty/draft-guide-arquillian-managed#25]
From @chyt: I do not believe using “RELEASE” for a parent dependency is valid - see https://stackoverflow.com/a/1172371/634324
EC: The team will determine and handle this all together in multipane.

**Comment by yeekangc** [comment]
Maven doesn't have support for version ranges straight in all the needed places.  Yes, some of these have been deprecated.  Then, there isn't a clean solution yet.  We will update as appropriate.

**Comment by evelinec** [comment]
There's an issue on guides-common to handle this for all guides, https://github.com/OpenLiberty/guides-common/issues/200. Close this one.
