### ISSUE TITLE
Multipane feedback

### ISSUE THREAD

**Issue by justineechen** [OpenLiberty/draft-guide-arquillian-managed#35]
- [x] In `Try what you'll build`, we usually don't say `cd finish` in the command I think it's generally described in the sentence above that command to ask users to go to the finish directory
ex. https://qa-guides-multipane.mybluemix.net/guides/microprofile-openapi.html#getting-started
- [x] In `Developing Arquillian tests`, the two links: `http://localhost:9080/{WARNAME}/inventory/systems/{hostname}` and `http://localhost:9080/{WARNAME}/inventory/systems` shouldn't be backticked and they can be made unclickable by using a backslash before the url '\' since they need to put in the WARNAME and also you aren't asking the user to go to that URL
- [x] There are two "Nice work.. etc" at the bottom of the guide
EC: seems like a design issue

**Comment by evelinec** [comment]
@justineechen can you review the changes?
