### ISSUE TITLE
User Review

### ISSUE THREAD

**Issue by wojtczat** [OpenLiberty/draft-guide-arquillian-managed#37]
## What you’ll learn
- [x] "Arquillian test sets up the test environment" Is Arquillian Test supposed to be a proper noun? if so the t should be capitalized
## Developing Arquillian tests
- [x] "The ShrinkWrap test archive’s contents" this is not friendly to read so I would recommend rewording this
- [x] "The endpoint test case first calls the http://localhost:9080/{WARNAME}/inventory/systems/{hostname}" should this link be back-ticked? same thing with the other link in this paragraph
- [x] "CDI is used to inject an instance of the InventoryResource class into this test class." CDI seems to come out of nowhere and then isn't elaborated on much. To get a better understanding of what is happening maybe you could link the CDI guide or something since that isn't the focus of this guide
## Configuring your test build
- [ ] "First, configure your test build with Maven. All of the Maven configuration takes place in the pom.xml file." the hotspot on pom.xml doesn't highlight the pom.xml file
EC: this is the expected behaviour now that no highlighting for an entire file hotspot. But you can verify the hotspot is working, if you navigate to another file, hover over the hotspot will bring you back to this file. 
- [x] "liberty-maven-app-parent parent POM" kind of bothers me to read but I don't have that big of a problem with this if it cant be worded differently 
- [ ] sometimes pom.xml is used with a hotspot and at other times it is referred to as POM without a hotspot. I would pick one convention and be consistent. Personally, I prefer the hotspot with pom.xml
EC: when we first introduce the pom file, we refer to it as the `pom.xml` with hotspot. Any description of the pom after it's being introduced are generally referred to as POM, which is a technical term.
## Configuring the server.xml
- [ ] " at the src/main/liberty/config/server.xml file." should this have a hotspot on it? If it does have a hotspot shouldn't it just be on the file name instead of providing a hotspot for the entire path. Also this doesn't highlight the file either
EC: this is the expected behaviour now that no highlighting for an entire file hotspot. But you can verify the hotspot is working, if you navigate to another file, hover over the hotspot will bring you back to this file. About the file path, we generally to show the entire file path when we refer to a file. Just the `pom.xml` is in the root directory, there's no additional path to show. 
## Nice work! Where to next?
- [ ] "Nice work!" Is being used to open both of the sentences in this section which makes this section look kind of funny. I believe you can remove the "nice work" from the second sentence 
Besides that everything else worked well. All of the links were accurate and all of the other hotspots worked. There was also a nice logical flow in the way concepts were presented. Good job!
EC: the "Nice work" problem is a known design issue. It will be fixed.

**Comment by evelinec** [comment]
@wojtczat thank you for your review! The relevant changes are made and refreshed on the test site. Pls check it out and verify. Thank you.

**Comment by wojtczat** [comment]
Looks good Eveline!
