### ISSUE TITLE
Review feedback

### ISSUE THREAD

**Issue by yeekangc** [OpenLiberty/draft-guide-arquillian-managed#40]
_What you’ll learn_
- [x] Arquillian Managed container vs Arquillian Liberty Managed container: Can we be consistent?  I lean toward Arquillian Manager container.  What's the difference between Arquillian Manager vs Arquillian Liberty Managed?
- [x] “Arquillian test sets up the test environment and is able to handle the application server life cycle for you” >> Arquillian sets up … We shouldn't need "test"
- [x] Arquillian Liberty Manager container adaptor?  What is this?

_Developing Arquillian tests_
- [x] “Its resource functionalities”: What does this mean?  I would consider a different term
- [x] `@Deployment block` does not need to be copyable
- [x]  What is ShrinkWrap?  What does it do and why?  (If this is to be explained later, I will rework these paragraphs.)
- [x] What are in-container tests?
- [x] “Notice the arquillian-managed.war WAR name in the web archive” >> Notice the arquillian-managed.war name used for the web archive
- [x] “This WAR name is also needed when the inventory service communicates with the system service to get the system properties.” — I don’t understand this and I don’t see it …
- [x] `@ArquillianResource` — How does a base URL for a web service relates to hostname, port number and even web archive information?  Is this how Arquillian sets things up?  If so, we should explain it as such.
- [x] Consider a better name for `testGetPropertiesFromFunction`?  This is a unit or whitebox test that tests or inspects the resource and its data directly?  The sample code has a different method name?!
- [x] “The sequences are important for the two test methods, as the results in the first test impacts the second one” >> The sequence is important for the two tests …

_Configuring Arquillian with Liberty_
- [x] “Configure your build to use the Arquillian Liberty Managed container and set up the Liberty server.xml file to run your test cases with Open Liberty” >> Configure your build to use the … and set up your Open Liberty server to run your test cases by configuring the server.xml file
- [x] If the user does not need to take any action in this section, we need to call out that all the files have been provided for them.
- [x] We should phrase the steps as actions that users should take (even if we have done it for them).  Otherwise, it is confusing to figure out what to do when users need to do them themselves.  We should rephrase all the First, Next, Next etc.  Call out the why too.
- [x] Should split maven-failsafe-plugin and liberty-maven-plugin into 2 sections.
- [x] Where do these come from?  Sudden mentions of wlpHome, serverName, httpPort?  Why should the user care?  What are they?  I don’t see them in the plugin configuration provided?
- [x] Where is `arquillianProperties` dictionary?  I don’t see it in the sample provided.
EC: this is an optional step. If user wants to add additional parameters in their `arquillian.xml` file, those can be specified using the `arquillianProperties` dictionary/block. The sample doesn't have any additional parameters, thus it's not demonstrated. For this reason, this phase is removed to avoid confusion. 
- [x] What is “Liberty Maven Application Parent”?  Let us use consistent terminology throughout.
- [x] If “the test server configuration is disabled” is referring to the effect of `skipTestServer`, we should use consistent terminology or join the sentences somehow.

- [x] I don’t think “in the featureManager block” is necessary and it can make it confusing to read too.  And, I will write as actions.  The action here is basically to configure these 2 features in your server.xml to run your tests with Arquillian.
- [x] `<!— Arquillian test feature —>`: This comment is misleading.  We should rephrase.  These are features needed by Arquillian but they are generally useful too.  They aren’t any test features for Arquillian or any feature created specifically for Arquillian.

_Running the tests_
- [x] Should we provide a sample output?  Relevant portions of it.
- [x] I find the term, ShrinkWrap web archive, confusing.

_Great work! You’re done!_
- [x] If we are using the terms, functional and integration, we should use them consistently throughout including in the code e.g. for test method names and class names as appropriate.

- [x] Btw, what’s the proposed SEO title and description?  What's there currently could use improvements?

**Comment by yeekangc** [comment]
@gkwan-ibm

**Comment by gkwan-ibm** [comment]
For the following paragraph,
- All of the packages in this service must be added to the web archive; otherwise, the code compiles successfully but fails at runtime when the injection of the testing resource class takes place. You can learn about the ShrinkWrap archive configuration in the Arquillian guide.

Before the work ShrinkWrap, no description about what it is, so as I am a reader, it may confuse why need to learn it from the link provided

I would suggest to say something.... (Please correct if it is not technically right)
- Use ShrinkWrap to create the web archive which will be deployed by the Arquillian when running the tests. Add all of the packages for the service to be tested to the web archive. Otherwise, the code can be compiled successfully but it will fail at runtime when the injection of the testing resource class takes place. You can learn about the ShrinkWrap archive configuration in the Arquillian guide.

**Comment by gkwan-ibm** [comment]
For the following paragraph in the "Configuring Arquillian with Liberty" section,
- You also need the `arquillian-liberty-managed-junit` dependency bundle and the Arquillian `shrinkwrap-api`. The dependency bundle includes all the core dependencies for running Arquillian tests on a managed Liberty container using JUnit. You can learn more about the **Arquillian Liberty dependency bundles**. The Shrinkwrap API allows you to create your test archive which is packaged into a WAR file and deployed to the Open Liberty server.

I would suggest to rearrange as ...
- Then, you need the `arquillian-liberty-managed-junit` dependency bundle, which includes all the core dependencies for running Arquillian tests on a managed Liberty container using JUnit. You can learn more about the **Arquillian Liberty dependency bundles**. You also need the `shrinkwrap-api` dependency. The Shrinkwrap API allows you to create your test archive which is packaged into a WAR file and deployed to the Open Liberty server.

**Comment by gkwan-ibm** [comment]
For the following:
- Finally, you need the maven-failsafe-plugin to run your Arquillian integration tests using JUnit.
 You also need the liberty-maven-plugin configuration ...

The "Finally" is not really a final need.

**Comment by gkwan-ibm** [comment]
For the following:
- You can learn more about the configure-arquillian goal in the documentation. 

I would suggest to change the word documentation as ...
- You can learn more about the configure-arquillian goal in the **WASdev/ci.maven document**.

**Comment by gkwan-ibm** [comment]
For the "Configuring the server.xml" section, if don't want to modify the server.xml, I prefer either to replace the server.xml or provide the server.xml, then explain the Arquillian required features (do something as the pom.xml)

**Comment by gkwan-ibm** [comment]
> EC: YK wants this one to be an action item. If you're ok with replacing the server.xml file, creating it from scratch should be ok too. :)

Replace is ok to me but not create

**Comment by yeekangc** [comment]
Doesn't mean that we have to create or replace.  We should write it in a way that call out and inform users what they need to do.  We didn't.

**Comment by yeekangc** [comment]
@evelinec @gkwan-ibm 

**Must fix**
```The method annotated by @Deployment defines the content of the web archive, which is going to be deployed to Open Liberty and the tests are run on or against the server. The testable = true attribute enables the deployment to run in-container tests, which means the tests are run against the server.```
Consider something like "The `@Deployment` annotated block of code defines the web archive that is to be deployed to the server. Tests are either run on or against the server. When the `testable=true` attribute is added, it means this test is running against the server."

```You also need the liberty-maven-plugin configuration that specifies your Open Liberty runtime and uses the configure-arquillian goal to automatically create and configure your arquillian.xml file. This goal retrieves the core wlpHome, serverName, and httpPort parameter values automatically from the Liberty Maven plug-in configuration, and also allows you to specify additional arquillian.xml parameters directly in your POM. You can see the parameter values in your arquillian.xml file after you run your tests. The parameter values are needed to run the Arquillian Liberty Managed container tests. You can learn more about the configure-arquillian goal in the documentation. ```
The portion about arquillian.xml is still confusing since we don't show it.  It's hard to picture what are these parameter values and why one needs to care.

**Should fix**
```Contexts and Dependency Injection (CDI) is used to inject an instance of the InventoryResource class into this test class. You can learn more about CDI in the Injecting dependencies into microservices guide.```
InventoryResource should be a hotspot?

**Later**
"You need" is used multiple times in "Configuring Arquillian with Liberty".  We can improve the writing style.  Also, the "Finally" step isn't really final (as noted above)?

"Nice work" is repeated under "Nice work! Where to next?", which is unnecessary?

I will submit a PR for the use of "Arquillian Liberty managed container" as soon as I can.

**Comment by yeekangc** [comment]
```The @ArquillianResource annotation is used to retrieve the http://localhost:9080/arquillian-managed/ base URL for this web service. The annotation provides the host name, port number and web archive information for this service, so you don’t need to hardcode these values in the test case. Notice the arquillian-managed WAR name that was specified in the web archive, it’s needed when the inventory service communicates with the system service to get the system properties.```

The last sentence can use a revision.  It's difficult to see and understand the connection between _the arquillian-managed WAR name that was specified in the web archive_ and what is in the prior sentences.

**Comment by evelinec** [comment]
@yeekangc Addressed the above comment in #48. Can you pls take a look? Thanks.

**Comment by evelinec** [comment]
@yeekangc can we close this issue? Thanks.
