### ISSUE TITLE
ID review feedback

### ISSUE THREAD

**Issue by evelinec** [OpenLiberty/draft-guide-arquillian-managed#51]
Hi!
Here are my review comments for the guide. If you have any questions, feel free to sametime me or slack me.

Global change: Make sure that you are using the name of the container consistently. You might be referring to two containers, the more general "Arquillian managed container" and the Liberty version of the container-  the "Arquillan Liberty managed container". If they are two different containers, then make sure that you use their names consistently. If it is one container, then use the same name throughout the guide. In some cases "Managed" is capitalized in the guide. Use lower case instead. 

Change the title of  "Testing microservices with Arquillian managed container" to "Testing microservices with the Arquillian managed container".

Change "microservices using the" to "microservices by using the".

Change ".... and is able to handle the application server lifecycle for you, so you can focus on writing tests." to "... and handles the application server lifecycle for you so that you can focus on writing tests.".

Change "In this guide, you will develop Arquillian tests that use JUnit as the runner and build your tests with Maven using the Liberty Maven plug-in, which simplifies the process of managing Arquillian dependencies and the setup of your Arquillian managed container." to "You will develop Arquillian tests that use JUnit as the runner and build your tests with Maven by using the Liberty Maven plug-in. This technique simplifies the process of managing Arquillian dependencies and the setup of your Arquillian managed container.".

Change "The application that you will work with is an inventory service that stores information about various systems. " to "You will work with an inventory service application, which stores information about various systems. ".

Change "and stores them. " to "and store them. ".

Change "You will also learn about the Maven and server configurations you need to run your tests " to "You will also learn about Maven and server configurations so that you can run your tests ".

Change "To try running the finished " to "To run the finished ".

Change "You should see the console output indicating that your build is successful and the tests have passed. " to "In the console output, search for an indication that the build was succesful and that the tests passed. ".

Change "The code for the microservices is provided to you under the " to "The code for the microservices is in the ".

Change "Navigate to the start directory to begin.
Create the InventoryArquillianTests test class." by first moving "Create the InventoryArquillianTests test class" out of the highlighted area. Then change the wording to "In the start directory, create the InventoryArquillianTests test class.".

Change "Notice the JUnit Arquillian runner is being used to run the tests, instead of the standard JUnit runner. The @RunWith annotation at the top of the class tells JUnit to run the tests using Arquillian." to "Notice that the JUnit Arquillian runner runs the tests instead of the standard JUnit runner. The @RunWith annotation preceding the class tells JUnit to run the tests by using Arquillian.".

Change "The testable = true attribute enables the deployment to run the tests "in container", that is the tests are run on the server." to "The testable = true attribute enables the deployment to run the tests on the server.".  

Change "name used for the web archive. " to "name that is used for the web archive. "

Change "This is necessary if " to "This name is necessary if ".

For "ShrinkWrap is used to create..." we want to say what ShrinkWrap is. From reading the paragraph and going out to the web, how about if we start it with "The ShrinkWrap archive configuration is used to....". Or might if some other noun should follow "ShrinkWrap", for instance "class", then use that noun instead.

Change ".... the client side, which means the tests are run against the managed container." to "....the client side. By running the tests on the client side, the tests are run against the managed container. ".

Change "The test checks that the inventory should have one host and that should be localhost." to "The test checks that the inventory has one host and that the host is localhost.".

How about if we split the paragraph starting with "Contexts and Dependency Injection (CDI) is used ..." into two paragraphs. So for, the first paragraph, keep "Contexts and Dependency Injection (CDI) is used to inject an instance of the InventoryResource class into this test class. You can learn more about CDI in the Injecting dependencies into microservices guide.". 

For the second paragraph, let's change the first sentence a little. Change "The instance is then tested by the ..." to "The InventoryResource instance is tested by the...."

Change "...method to get all systems are stored in... " to "...method to get all systems that are stored in...". 

Change "by configuring the server.xml. " to "by configuring the server.xml file.".

The meansing for "Using JUnit" is a bit ambiguous.  I believe what is meant is "that uses JUnit." However, possibley, "by using JUnit" was meant. Change the wording to the correct wording. For instance, change "...Arquillian tests on a managed Liberty container using JUnit." to "....Arquillian tests on a managed Liberty container that uses JUnit.".  

Move "You can learn more about the Arquillian Liberty dependency bundles." to the end of the paragraph.

Change "your test archive which is packaged" to "your test archive, which is packaged". (Add a comma.)

Change "The maven-failsafe-plugin runs your Arquillian integration tests using JUnit. " to "The maven-failsafe-plugin artifact runs your Arquillian integration tests that use JUnit. ". (or "by using JUnit, as appropriate)

Change "You can learn more about the configure-arquillian goal in its documentation." to "You can learn more about the configure-arquillian goal.".  <= make "configure-arquillian goal" the link.

For ".... the skipTestServer element is set to true to skip....", highlight "true" like you have highlighted other text since "true" is a value.

Change "Also, notice in..." to "Notice in...".

Change the title of "Configuring the server.xml" to "Configuring the server.xml file".

Change "Maven build, setup your " to "Maven build, set up your ".

Change "you see the application server was launched, and the web archive, archive, arquillian-managed, is started as an application in the server." to "you can see that the application server launched, and that the web archive, arquillian-managed, started as an application in the server. ". <= Add "that" twice.

Change "Then, the tests are being run and the results are reported." to "You can also see that tests are running and that results are reported.".

Change "Following the execution of the tests, the test application is automatically undeployed and the server is shut down." to "After the tests stop running, the test application is automatically undeployed and the server shuts down.".

Change "You have just built..." to "You just built ...".

Change ...with the Arquillian Liberty Managed container..." to "...with the Arquillian Liberty managed container ..." or   "...with the Arquillian managed container ...".

Change "You can continue to try one of the related guides..." to "Try one of the related guides...".

**Comment by evelinec** [comment]
About the follow point, "Arquillian managed container" is the generic term for managed container type of Arquillian tests. The "Arquillian Liberty Managed container" is the Liberty adopter to do "Arquillian managed container" testing. They're essentially the "same" managed container. The capitalized word "Managed" was only used when the term "Arquillian Liberty Managed container" is used, as that's the way Liberty has it. 

Global change: Make sure that you are using the name of the container consistently. You might be referring to two containers, the more general "Arquillian managed container" and the Liberty version of the container- the "Arquillan Liberty managed container". If they are two different containers, then make sure that you use their names consistently. If it is one container, then use the same name throughout the guide. In some cases "Managed" is capitalized in the guide. Use lower case instead.

**Comment by yeekangc** [comment]
@chirp1 ^^^

If we need to pick, I lean toward using "Arquillian managed container" and where necessary, we qualify it as "Arquillian managed container for Liberty".

We can have an instance of "Arquillian Liberty Managed container" in the SEO description if appropriate.

**Comment by evelinec** [comment]
Some comments about the following feedback: 

Change "To try running the finished " to "To run the finished ".
=> changed to the common adoc way. We really want to show that this is a "try" section. Getting rid off the word "try" is as intuitive. 

Change "You should see the console output indicating that your build is successful and the tests have passed. " to "In the console output, search for an indication that the build was succesful and that the tests passed. ".
=> changed to "In the console output, you can see the build was succesful and the test passed."  We don't need "search for an indication". 

Change "Navigate to the start directory to begin.
Create the InventoryArquillianTests test class." by first moving "Create the InventoryArquillianTests test class" out of the highlighted area. Then change the wording to "In the start directory, create the InventoryArquillianTests test class.".
=> Moved the "Navigate to the `start` directory to begin." to the top of this section, which makes sense, as the file path is accessible within the `start` directory. The "Create a ... class." wording in the highlighted area, is the new design for the multipane guide's layout. It's consistent for all guides now. 

Change "The testable = true attribute enables the deployment to run the tests "in container", that is the tests are run on the server." to "The testable = true attribute enables the deployment to run the tests on the server.".
=> The sentence you suggested made sense, just that we actually want to point out the "in container" concept in this paragraph. No change. 

Move "You can learn more about the Arquillian Liberty dependency bundles." to the end of the paragraph.
=> There's the ShrinkWrap API dependency description that is not part of the Arquillian Liberty dependency bundle. So moving the "learn more about the Arquillian Liberty dependency bundles" link to the end of the paragraph doesn't fit.

Change "You can learn more about the configure-arquillian goal in its documentation." to "You can learn more about the configure-arquillian goal.". <= make "configure-arquillian goal" the link.
=> I like the suggestion. Just that the syntax is not working that way. 
----You can learn more about the [hotspot=215]`configure-arquillian` goal in its
https://github.com/WASdev/ci.maven/blob/master/docs/configure-arquillian.md[documentation^].----
You can see there's a hotspot syntax that needs to be applied on the `configure-arquillian` goal, and the hyperlink syntax also requires a square blankets. The hotspot syntax makes it point to the code snippet. It can't be linked to a hyperlink at the same time. 

All of the others points were addressed.

**Comment by evelinec** [comment]
@gkwan-ibm can you review this ID feedback PR and responses to some of them? Thanks.
