### ISSUE TITLE
Content review

### ISSUE THREAD

**Issue by evelinec** [OpenLiberty/draft-guide-arquillian-managed#6]
- [x] Not sure the word "Managed" needs to be camel cap'ed
- [x] Add more content to the intro
- [x] Address the structure and style for the content to be consistent with the new UI design as well as other guides
- [x] fix travis.yml and enable automation to be consistent with other guides
- [x] minimize the use of future tense and passive voice

**Comment by chyt** [comment]
Sorry, what does "camel cap'ed" mean?
