### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by justineechen** [OpenLiberty/draft-guide-arquillian-managed#8]
**Configuring your test build**
- [x] It may be useful to tell the user to "Navigate to `start` directory" ... and then to modify the `pom.xml`
- [x] Normally in OL guides, we ask users to create the entire file so it's easy for them to copy and paste. And then later on, we explain the important parts within the file rather than have them copy and paste bits into the file. For `pom.xml` and `build.gradle`.
Maybe take a look at MP-JWT and how the author provided a table to describe parts of their xml file
https://openliberty.io/guides/microprofile-jwt.html

**Configuring the server.xml**
- [x] "Now that you’re done configuring the build tool of your choice, create the `src/test/resources/server.xml` file:"

**Adding your Arquillian test**
- [x] Omit the copyright tags when you display code

It may be helpful to take a look at:
https://github.com/OpenLiberty/draft-guides-template/wiki/Guidelines-for-Structure-and-Styles
Specifically, Project Structure and Explaining the code.

**Comment by evelinec** [comment]
@justineechen can you review the latest guide and let me know if there're any issues? Otherwise, close this one. Thanks.

**Comment by justineechen** [comment]
Thank you! My points from above have been addressed.
Is there a better wording for the hyperlink "complete documentation" in `Configuring Arquillian with Liberty`?
